### ISSUE TITLE
Unable to move items up in sortable list

### ISSUE THREAD

**Issue by smartmeter** [mcintyre321/FormFactory#10]
//ICollections get rendered as re-orderable lists
        public ICollection<Movie> TopMovies { get; set; }

Love it!!

1.     The corresponding code does not sort up, i.e. try to move a list item up, it does not move up. How does the list know to sort, in the code, I see no configuration.
2.     How is security handled, is just standard role checking at the class level, I ask because it would be nice to have a way to map roles to forms and models. (I'll add it o the feature request :)

**Comment by mcintyre321** [comment]
1. Hmm not sure how that bug has crept in, will check it out on Monday.
It's all done in Formfactory.js or in in-line script tags in the templates

2. I use another lib of mine, called Harden to do per property security,
although it needs hooks to work on recursive properties.

**Comment by mcintyre321** [comment]
Cheers for spotting that, there was a typo in the template. Fixed!
