### ISSUE TITLE
Usage question

### ISSUE THREAD

**Issue by mcintyre321** [mcintyre321/FormFactory#11]
From [StackOverflow](http://stackoverflow.com/questions/17229514/asp-net-mvc-4-dynamic-forms/30081059?noredirect=1#comment52203050_30081059)

	
> Hi, 
> 1) in this snippet using (var form = Html.FormForAction((HomeController c, string p0, string p1, bool > p2, string p3) => c.SignIn(p0, p1, p2, p3))) there are 4 vairables, but the action takes 3 variables, 
> 2)How is the submit being performed in the second form, can you expand the documentation a little please
> 3) how can I do Lat Long, Fa-Icons? –  aggie yesterday

**Comment by mcintyre321** [comment]
1. Think the docs are out of date, it should just have two properties. You can see how that code works in (FormHelperExtension.cs)[https://github.com/mcintyre321/FormFactory/blob/master/FormFactory.AspMvc/FormHelperExtension.cs]. I think in new versions I might get rid of the Expression based helper, and use the `nameof` operator to do strong typing.

2. It's just a standard form and controller action [Index.cshtml](https://github.com/mcintyre321/FormFactory/blob/master/FormFactory.Example/Views/Home/Index.cshtml)
``` c#
            <form action="/home/save" method="POST">
                @{
                    if (string.IsNullOrWhiteSpace(Request.Params["UseRazorEngine"]))
                    {
                    @(Html.PropertiesFor(Model).Render(Html))
                    }
                    else
                    {
                        var helper = new FormFactory.RazorEngine.RazorTemplateHtmlHelper();
                        var propertiesFor = helper.PropertiesFor(Model);
                    @Html.Raw(propertiesFor.Render(Html)) //needs to be made raw as we are in MVC
                    }
                }
                <input type="submit" value="submit" />
            </form>
```

3. You'd need to create your own type MyProject.LatLng, and a template at /Views/Shared/FormFactory/Property.MyProject.LatLng.cshtml

What do you want to do with fa-icons?

**Comment by smartmeter** [comment]
be able to show fa-icons as components in the forms images or interactive SVG elements, but thats not all that important, just pretty :)
:+1:

**Comment by mcintyre321** [comment]
You can override the templates yourself, or one trick I use for customisation is to take the HTML output, feed it into CsQuery, transform it, then render it.
