### ISSUE TITLE
Could the database operations be dynamic too?

### ISSUE THREAD

**Issue by abdoady** [mcintyre321/FormFactory#20]
I wonder how to make database operations dynamic, have you done such example?

**Comment by mcintyre321** [comment]
I'm not sure what you mean! You might be looking for the [UpdateModel](http://stackoverflow.com/a/14511480) method in ASP MVC?

**Comment by abdoady** [comment]
I mean on form submit, do we need to define a database table for each viewModel we created? For example if I'm about to submit the AutoCompleteExample form, do I need to create a db table(location, country) to save data, or you have a better approach for that?

**Comment by mcintyre321** [comment]
Maybe you are looking for a schema free NOSQL database like mongodb You
should ask questions like this on stackoverflow.com though, as this is a
general programming question.
