### ISSUE TITLE
Async methods support?

### ISSUE THREAD

**Issue by Bundas** [mcintyre321/FormFactory#21]
Hi, form factory supports only synchronous `ActionResult` type. Do you plan to add `async Task<ActionResult>`?

I mean `Html.FormForAction`

**Comment by mcintyre321** [comment]
I've been developing on an as-needed basis, and have no yet needed that feature in my code. I'm happy to accept a pull request with an overload for async ActionResults though.

**Comment by mcintyre321** [comment]
You can probably write your own
