### ISSUE TITLE
Choices rendering incorrectly

### ISSUE THREAD

**Issue by simonjudoduff** [mcintyre321/FormFactory#23]
When there are a set of choices defined on the ViewModel, the selectlist correctly displayed, but the options are also rendered as a bullet list.
It looks like the properties are not being selected to exclude _choices properties correctly.

**Comment by simonjduff** [comment]
Looks like a regression in ed6d6a94bc0c1fce5f1d064c4964f9b52a99f2f2 where you'd refactored at some stage "Choices" to become "_choices" but missed a reference when it came to skipping the property
