### ISSUE TITLE
Caching generated views

### ISSUE THREAD

**Issue by cezarlamann** [mcintyre321/FormFactory#29]
Hi!

I was reading FF code yesterday and a doubt appeared: Does FF generate views everytime it receives a request? Does it have a way of caching/storing generated views somewhere else (ie: Database or file)?

I have a lot of register/fields metadata stored in a database, and I'll use IL Generation for the classes with all data annotations, restrictions and validations. I'll hash these classes so, with every created field, there will be a new version of the same class, stored inside database.

Thank you for all effort put in this project.

**Comment by mcintyre321** [comment]
When using the aspmvc package, asp MVC will cache the views.

When using razor generator (standalone without MVC), I'm not 100% sure.

The reflection process is executed every time, although could probably be cached
