### ISSUE TITLE
Cant open project in VS2013 or VS2015

### ISSUE THREAD

**Issue by aap21** [mcintyre321/FormFactory#31]
Cant open project in VS2013 or VS2015

The formfactory XProj cant be loaded, FormFactory.AspnetCore cant be loaded and FormFactory.AspnetCore.Example wont load

What version of Visual Studio are you using?

**Comment by mcintyre321** [comment]
Have you got dotnet core SDK installed?

https://www.microsoft.com/net/core#windows

**Comment by aap21** [comment]
Hi

Thanks. I got it to work.

**Comment by mcintyre321** [comment]
Great. If you've got any more questions, ask away!
