### ISSUE TITLE
Disable edit for 1 or all property

### ISSUE THREAD

**Issue by scinfu** [mcintyre321/FormFactory#33]
Hi,
How can i disable edit for 1 or all property?
The goal is to let user see the property but not edit it , like for property in readonly .
Thank you

**Comment by mcintyre321** [comment]
`
     [Description("Readonly properties are rendered as readonly")]
     public int DaysSinceStartOfYear { get { return DateTime.Today.DayOfYear; } }
`

or you can do it in the view:

@FF.PropertiesFor(someObject).Render(Html);


```
@{
var properties = FF.PropertiesFor(someObject);
properties.Single(p =>p.Name == "someProperty").ReadOnly = true;
@properties.Render();
}

```
