### ISSUE TITLE
How to use this in WebForms?

### ISSUE THREAD

**Issue by A-Programmer** [mcintyre321/FormFactory#35]
Hello.
I wanna know if i can use this or something like this in WebForms, i need it very much, if you have idea or article or sample please give me.
Thank you

**Comment by mcintyre321** [comment]
I would have thought you can use this in an aspx if the MVC libraries are
installed in the project.

If not, then the RazorEngine package should work

**Comment by JoseRivas1998** [comment]
How would this be done?

**Comment by mcintyre321** [comment]
`<%= FF.PropertiesFor(SomePropertyOnThePage).Render(Html).ToString() %>
