### ISSUE TITLE
LabelOnRightAttribute usage

### ISSUE THREAD

**Issue by Budsy** [mcintyre321/FormFactory#37]
I tried adding new FormFactory.Attributes.LabelOnRightAttribute() to the GetCustomAttributes field list (in declarative programmable model example) for a checkbox. It rendered the following:

"if (Model.GetCustomAttributes().OfType ().Any()) {  } else //if not required, then it is possible to post a false value, which means we need a hidden field as unchecked checkboxes aren't posted. sigh. {   } Checkbox label here"

This wasn't quite what I expected. Is there a correct way to get the label for a checkbox to render to the right of the box? A checkbox works great with the default label on the left.

**Comment by mcintyre321** [comment]
Thanks for trying out. It seems to be rendering the raw template instead of
rendering it properly. There may be a missing @ somewhere.

Could you fork the project and add your code to the examples and I will
take a look ASAP?

**Comment by Budsy** [comment]
I put my code into the Mvc Examples Index demo page on a fork. Currently I'm going to try to compile your source and track this down. ...have to upgrade my VS first. ;-)

**Comment by Budsy** [comment]
I found the bug and made a fix in FormFactory/Views/Shared/FormFactory/Property.System.Boolean.cshtml . It was, as you surmised, missing the @ on the if keyword, needed after the  html <label> tag line in the View markup file. I compiled the Dll with this change and am using it in my project now. Works like a charm.

**Comment by mcintyre321** [comment]
thanks for the PR!
