### ISSUE TITLE
Embedded resource feature

### ISSUE THREAD

**Issue by Budsy** [mcintyre321/FormFactory#40]
This may just be an issue with my setup, but... when I got around to publishing my web project to a staging site, I discovered that the 'Embedded Resource' feature completely stopped working, unable to find the virtual paths for some reason. The dev version and the staging version of my app are as identical as I can make out, right down to asp.net version and server configuration parameters. I checked all the Dlls and files list, and everything seems to be there. I updated my nuget packages, checked my Mvc routing, checked versioning, etc. etc. Obviously some little detail is missing. Anyway, I worked around this issue by eliminating the Embedded resource files and references, then installed all the template files. This seems to work just fine now in terms of speed and whatnot, and I can tweak the templates more easily. I just wanted to share this experience.

**Comment by mcintyre321** [comment]
Did you have the VPP installed?

**Comment by mcintyre321** [comment]
I guess you must have if it works locally... hmm

**Comment by mcintyre321** [comment]
Are you using Core or MVC5? You need a bit of config for Core.

**Comment by Budsy** [comment]
Just using MVC5. Yes, it is working well locally. I'm letting it stay that way for this project until I figure out this oddity.

**Comment by mcintyre321** [comment]
Closing this as it's so old
