### ISSUE TITLE
How to handle form submit + put values into a view model

### ISSUE THREAD

**Issue by juanonsoftware** [mcintyre321/FormFactory#45]
Hello,
FF works great when creating a form programatically (fields are displaying well).
But when I submit the form, I'd like to find a efficient way to bind to the model. Do you have an example about this? Or any suggestion?
Thanks

**Comment by mcintyre321** [comment]
What Type is the model? Do you have examples of the data?

If it's not a Type (e.g. it's data driven), you can use a ModelBinder that
binds to JObject* then use code to take values from the JObject.

If you get stuck (or even if you get it working!) you could add an example
to the Example app and i can take a look


* I think I've found one on Google in the past

**Comment by juanonsoftware** [comment]
In fact I try your example on "Programatically created form". So the model is dynamic, it will have field define dynamically. I have created a custom ModelBinder and it works on basic types (manually convert from string to the type I want and put values into a Dictionary).

**Comment by mcintyre321** [comment]
Nice, that's a good solution.
