### ISSUE TITLE
Programmatically Created Form - Nested Forms Example

### ISSUE THREAD

**Issue by janamargaret** [mcintyre321/FormFactory#50]
Hello! Do you have any code examples of how to get either of the Nested Forms examples on [http://formfactoryaspmvc.azurewebsites.net/)](http://formfactoryaspmvc.azurewebsites.net/) working for a Programmatically Created Form?

**Comment by mcintyre321** [comment]
No... I think you can maybe use an object as the outer item:

```

    new PropertyVm(typeof(object), "outer") //<!- 
     {
         DisplayName = ...,
         Value = ... inner PropertyVm[] ,
         ...
    {
}

**Comment by stumpk** [comment]
Thanks for the great work. Sorry if I am doing something obviously wrong, I've just started playing with FromFactory.
I am trying to do this as well, but when I put a PropertyVm array in for the Value of the object, I am System.StackOverflowException. Any ideas what I am missing?

Thanks

**Comment by mcintyre321** [comment]
Can you send me a code snippet please?

**Comment by stumpk** [comment]
Of course. Right now I am just playing around with the example code. Please see below:

     
           var lasers = new[] {
                 new PropertyVm(typeof(string) , "Left")
                    {
                        DisplayName = "Left",
                        NotOptional =true,
                        GetCustomAttributes = () => new object[] { new DataTypeAttribute("TitleTol") }
                    },
                  new PropertyVm(typeof(string) , "Right")
                    {
                        DisplayName = "Right",
                        NotOptional =true,
                        GetCustomAttributes = () => new object[] { new DataTypeAttribute("TitleTol") }
                    },
                   new PropertyVm(typeof(string) , "Ceiling")
                    {
                        DisplayName = "Ceiling",
                        NotOptional =true,
                        GetCustomAttributes = () => new object[] { new DataTypeAttribute("TitleTol") }
                    },
                    new PropertyVm(typeof(string) , "Sagital")
                    {
                        DisplayName = "Sagital",
                        NotOptional =true,
                        GetCustomAttributes = () => new object[] { new DataTypeAttribute("TitleTol") }
                    },
            };
         

            var formModel = new[]
           {
                    new PropertyVm(typeof(object) , "outer")
                    {
                        DisplayName = "Laser Alignment",
                        NotOptional =true,
                        Value=lasers
                    },
                  
              };

**Comment by mcintyre321** [comment]
Ah I can see the problem. PropertyVms aren't designed to be nested, instead they should be rendered as a flat list.

If you want to do what you are after, try putting the parent item name into each PropertyVms name e.g. for `Left`, use `outer.Left` :

```
var lasers = new[] {
             new PropertyVm(typeof(string) , "outer.Left")
                {
                    DisplayName = "Left",
                    NotOptional =true,
                    GetCustomAttributes = () => new object[] { new DataTypeAttribute("TitleTol") }
                },
              new PropertyVm(typeof(string) , "outer.Right")
                {
                    DisplayName = "Right",
                    NotOptional =true,
                    GetCustomAttributes = () => new object[] { new DataTypeAttribute("TitleTol") }
                },
               new PropertyVm(typeof(string) , "outer.Ceiling")
                {
                    DisplayName = "Ceiling",
                    NotOptional =true,
                    GetCustomAttributes = () => new object[] { new DataTypeAttribute("TitleTol") }
                },
                new PropertyVm(typeof(string) , "outer.Sagital")
                {
                    DisplayName = "Sagital",
                    NotOptional =true,
                    GetCustomAttributes = () => new object[] { new DataTypeAttribute("TitleTol") }
                },
        };
```
