### ISSUE TITLE
Need help with usage

### ISSUE THREAD

**Issue by gingters** [mcintyre321/FormFactory#55]
Hi,
i'm trying to use FormFactory in one of my open source projects.
I like it how it generates my first form, but I'm a bit lost in how to use the features.
I am using ASP.NET Core 2 Razor Pages.

So my main two questions are:
How can I enable validation? My required fields i.e. aren't validated and I can post the form without needing to fill in required fields.

When the form gets posted, what do I need to do to get the entered & posted data into my model to further process it?

Thanks in advance

**Comment by mcintyre321** [comment]
Have you included the unobtrusive validation javascript script? It's
required for the validation to work. See the source of the example page.

It should bind to the view model in the same way a normal form is bound (or
are you using a dynamically built form?)

**Comment by gingters** [comment]
Ah, all sorted out. Indeed, the javascript was missing. I could also sort out the binding. Thanks.
