### ISSUE TITLE
Programatic Buttons

### ISSUE THREAD

**Issue by SignalRT** [mcintyre321/FormFactory#58]
I'm trying to figure how to build a form programatically (with success), but I have no success trying to make appear the Summit button and trying to get the form values to the FormVm dynamic object that I create to build the form.

I would appreciate some tips on this.

**Comment by mcintyre321** [comment]
You can just manually create the submit button yourself. If you bind to a JToken (using [https://github.com/mcintyre321/AspNetCoreJTokenModelBinder](https://github.com/mcintyre321/AspNetCoreJTokenModelBinder)for dot net core) you can save the data off - don't bother trying to bind back to the FormVm/PropertyVms

**Comment by SignalRT** [comment]
Thank you. All the suggestions are working fine.
