### ISSUE TITLE
Dependencies of default FormFactory templates

### ISSUE THREAD

**Issue by corstian** [mcintyre321/FormFactory#60]
I am getting a bit lost with the dependencies for the default templates with FormFactory. I see that I can modify these templates in order to implement the behavior and styles I want, but it does not seem to work out of the box.

Is there a list of javascript libraries the FormFactory templates depend on?

**Comment by mcintyre321** [comment]
I think they should be all referenced in the example site - living
documentation ;) !

**Comment by corstian** [comment]
Hahaha alright, will check! Mind if I create some wiki page describing dependencies for the default templates, if I have time and figure it out?

**Comment by mcintyre321** [comment]
Very very happy to have doc contributions!

I do favour having the documentation in the example site though, so that it
is versioned alongside the code. Could you add the info to a doc in the
source, then link to it from the wiki?
