### ISSUE TITLE
New Project - Enterprise Solution - Can forms be database driven?

### ISSUE THREAD

**Issue by johntallon** [mcintyre321/FormFactory#66]
Hi, 

Note: this is a question, not an issue. 

Is this Repo production ready, I have viewed the code and examples, and it looks very promising. One question i have is can the forms be generated at runtime driven from the data in a database? 

As this is attribute driven, does that limit the forms to be bassed the attributes are assigned at design time? 

Regards
John

**Comment by mcintyre321** [comment]
If you look at the bottom on the example page, you can see an example of
the PropertyVm being built up programmatically. You can use this to build a
firm from data
