### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by frozenshadow** [mcintyre321/FormFactory#67]
Is there a possibility to translate/localize the validation messages (e.g. RequiredAttribute)?

**Comment by mcintyre321** [comment]
You'd have to extend it yourself, but I'm happy to accept pull requests for any functionality like that. What approach for translation are you using, resx?

**Comment by frozenshadow** [comment]
Thanks for the quick reply.
Currently I'm not using any translations yet, but I think I'll go for resx.

I don't have any experience with translating C# applications/websites, so that will be a challenge 😉
Once I got it working I will make a PR.

**Comment by mcintyre321** [comment]
Are you doing asp.net MVC or asp.net core?

**Comment by frozenshadow** [comment]
asp.net MVC

**Comment by frozenshadow** [comment]
I made a working version for my project: https://github.com/frozenshadow/FormFactory.
Since I've never made a (NuGet) package before, I don't know what the requirements are.
So please let me know your thoughts ☺️

**Comment by mcintyre321** [comment]
Does the asp.net core example work on your machine?

**Comment by frozenshadow** [comment]
No idea. Haven't tried, modified or used that one.

**Comment by mcintyre321** [comment]
It uses shared code from the main FormFactory project, so they both need to have been checked before I can pull the code into my repositoryy.

If you open your solution, and start each of the example projects, you should see the documentation site. If that works, I can safely merge the code, and then update the main FormFactory Nuget package.

**Comment by frozenshadow** [comment]
Ah, thanks for the guide.

I’ll try and let you know next week.

 

And just realized I never thanked you for this awesome project.

A true one-of-a-kind that really helped me a lot the past months.

So a big THANK YOU!

 

Van: Harry McIntyre <notifications@github.com> 
Verzonden: vrijdag 27 juli 2018 16:58
Aan: mcintyre321/FormFactory <FormFactory@noreply.github.com>
CC: frozenshadow <contact@leijlandia.nl>; Author <author@noreply.github.com>
Onderwerp: Re: [mcintyre321/FormFactory] Localization (#67)

 

It uses shared code from the main FormFactory project, so they both need to have been checked before I can pull the code into my repositoryy.

If you open your solution, and start each of the example projects, you should see the documentation site. If that works, I can safely merge the code, and then update the main FormFactory Nuget package.

**Comment by mcintyre321** [comment]
Hey, thanks, that's great to hear!

I've got some ideas for FormFactory V2, but rarely get to chat to someone
who's family. If you fancy jumping on slack sometime, let me know.

**Comment by frozenshadow** [comment]
Yeah sure, would love to!

I've just tested the MVC and Core examples. And it seems to be working ok.
But just to be safe, maybe you should also check it ;)

**Comment by mcintyre321** [comment]
I'm more a 'rollback if necessary' kinda guy :)

**Comment by frozenshadow** [comment]
Haha!
You can sent me an invite for Slack if you want.
My mail is on my profile page.
