### ISSUE TITLE
Create button inside PropertyVM

### ISSUE THREAD

**Issue by ivansoriabia** [mcintyre321/FormFactory#70]
Hello!

How I can do to create a button in an PropertyVM. I have tried the answer that Harry posted in this [issue](https://github.com/mcintyre321/FormFactory/issues/58) but I have no idea about how to create a button in XElement.

****Please how I can make a button inside a PropertyVM, using XElement (or not using it if it's not done with XElement)?****
 
Thanks a lot.

**Comment by mcintyre321** [comment]
I think you should be able to do this:

```
	new PropertyVm(typeof(XElement), "number")
	{
		DisplayName = "A button",		
		Value = XElement.Parse("<button name='foo' />"), //or whatever html you want there
	}
```

**Comment by ivansoriabia** [comment]
Thank You!

I have do it like you have said and it's working as expected, so I will close this issue.
