### ISSUE TITLE
Localitzation and Validation Messages

### ISSUE THREAD

**Issue by ivansoriabia** [mcintyre321/FormFactory#73]
Hello Harry!

I'm finishing my project with FormFactory and I'm trying to validate the data from my inputs. In ASP .NET Core  you can set it like this:
 ````
public class SomeViewModel
{
    [Required(ErrorMessage = "Your elegant error message goes here")]
    public int ProductId { get; set; }
} 
````
But I haven't found any way to set it when I create my PropertyVms, so there is way to set my custom error message?

Another thing that I would like to change is the language that the **NotOptional / Optional Label** is shown. I would like to set it in Spanish.

Thank You!

**Comment by mcintyre321** [comment]
So you are creating PropertyVms programatically? You can add your own attributes:
e.g.
```
new PropertyVm(typeof(DateTime), "StartDate")
{
    DisplayName = "Start Date",
    Value = startDate
    GetCustomAttributes = () => new object[] {new DisplayFormatAttribute {DataFormatString = "dd/MM/yyyy"}]
},
```

So you can add a RequiredAttribute into the GetCustomAttributes Func

**Comment by mcintyre321** [comment]
I think to fix the optional message you'll have to either 
1. take your own custom version of [/Views/Shared/FormFactory/Form.Property.cshtml](https://github.com/mcintyre321/FormFactory/blob/d5f094fd3b01a31d5d760aaf50e22514ea3ddcd6/FormFactory/Views/Shared/FormFactory/Form.Property.cshtml) and modify it to have a hardcoded version

2, or take a fork, and modify mine to work of a resx file, and send me a Pull Request

**Comment by mcintyre321** [comment]
This PR already added a resx file 

https://github.com/mcintyre321/FormFactory/pull/68/files

**Comment by ivansoriabia** [comment]
So, I have to create a Resource file with all the values I want to translate and the make a pull request under FormFactory/Resources/ to be able to get this validation values in my form, don't I?

**Comment by ivansoriabia** [comment]
What I need to do to add Spanish translation to FormFactory?

**Comment by mcintyre321** [comment]
Being a Brit, I'm terrible at i18n, but have a read of this(see https://msdn.microsoft.com/en-us/library/fw69ke6f.aspx?f=255&MSPPError=-2147217396) and 

As I recall
1. add keys to the resx files for the text you want translated see [Resources.resx](https://github.com/mcintyre321/FormFactory/blob/master/FormFactory/Resources/Resources.resx#L120) and [Resources.es.resx](https://github.com/mcintyre321/FormFactory/blob/master/FormFactory/Resources/Resources.nl.resx#L120) - VS should give you a custom editor for doing this.

2. use the resource in https://github.com/mcintyre321/FormFactory/blob/master/FormFactory/Attributes/CompareAttribute.cs#L17

3. get your app to set the correct CurrentCulture

**Comment by mcintyre321** [comment]
I'm not sure, I'm not a big resx user.
