### ISSUE TITLE
Initial use

### ISSUE THREAD

**Issue by scriptmonkey69** [mcintyre321/FormFactory#79]
I am trying to use the FormFactory in a small **.NET Core** 2.2 demo, to get myself familiar with it before I go on an use it in a Cloud Multi tenant application.

I have followed the examples with regards to the Nuget packages installed and the javascript and css inclusions. I have also added the required code in the ConfigureServices and Configure methods in the Startup.cs to add the EmbeddedFileProvider.

Unfortunately it would seem the EmbeddedFileProvider is not providing files as I am getting the following error:
Property.System.Object.cshtml not found

Are there any pointers I have missed?

**Comment by mcintyre321** [comment]
Strange - if the project has the setup from the ASPNetCore Example, then it should work...

You can maybe get started by installing the FormFactory.Templates project, which should install the assets to disk.

**Comment by mcintyre321** [comment]
Hmm, I found the example project wouldn't load on Azure due to a new issue with views loaded from assemblies unless I added `  <MvcRazorExcludeRefAssembliesFromPublish>false</MvcRazorExcludeRefAssembliesFromPublish>` - maybe that needs to happen too

**Comment by scriptmonkey69** [comment]
Did you add that in the project file or the web.config?

**Comment by mcintyre321** [comment]
That's in the csproj. Only a problem for deployed code though, it should
all work locally.

Does the example project work locally for you?

**Comment by scriptmonkey69** [comment]
I will try it again tonight, and let you know. I have gone home so the demo project is still at work. It won't take long. 

Thanks for the quick response.

**Comment by scriptmonkey69** [comment]
Ok finally got back into the office and the example ASPN.NET Core project runs on my machine in debug mode.

So thanks for all the help and suggestions. Now to get it integrated into my solution.
I might need to raise some PRs for new templates, but will contact you as and when.
