### ISSUE TITLE
How to add FileUpload Object in Programatically created form?

### ISSUE THREAD

**Issue by fatihcelen** [mcintyre321/FormFactory#87]
Hi i look code but don't see any file upload attribute for input. how can i add file upload object in form.

**Comment by mcintyre321** [comment]
You can add either
- add an XElement with the correct tag and attributes to your viewmodel
- add your own cshtml template for a custom FileInput object that you would define

**Comment by fatihcelen** [comment]
When I add Property.BlaBla.FileUpload.cshtml in View Folder i get this error.

Severity	Code	Description	Project	File	Line	Suppression State
Error	NETSDK1022	Duplicate 'EmbeddedResource' items were included. The .NET SDK includes 'EmbeddedResource' items from your project directory by default. You can either remove these items from your project file, or set the 'EnableDefaultEmbeddedResourceItems' property to 'false' if you want to explicitly include them in your project file. For more information, see https://aka.ms/sdkimplicititems. The duplicate items were: 'Views\Shared\FormFactory\Property.BlaBla.FileUpload.cshtml'	FormFactory (FormFactory\FormFactory)	C:\Program Files\dotnet\sdk\2.1.509\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.DefaultItems.targets	257

**Comment by fatihcelen** [comment]
Is There any example for file input created with XElement programmatically.

**Comment by fatihcelen** [comment]
`  formModel.Add(new PropertyVm(typeof(XElement), "cFoto")
            {
                DisplayName = "Document Upload",
                Value = XElement.Parse("<input type='file' class='form-control' multiple='multiple' value='Upload'></input>")
            });`
