### ISSUE TITLE
No example provided for a server side validation

### ISSUE THREAD

**Issue by parvezdesignworks** [mcintyre321/FormFactory#97]
I am creating the properties programatically using the reference given on your website, but there this no example provided for server side validation.

There is no model driven form, I am using database driven form.

Can you please help me with a server side validation.

My forms will be user defined always.

**Comment by mcintyre321** [comment]
You need to do this yourself, i.e.

parse the input as a raw document, match the fields to the corresponding database records, and then run the appropriate validation rule.

You might find this useful https://github.com/mcintyre321/AspNetCoreJTokenModelBinder , although it might need an update for whatever version of ASP.NET core we are on now

**Comment by parvezdesignworks** [comment]
Thanks for your quick reply.

I have never done manual validation

Can you please provide some reference or put some more light on how to implement it.
